# Generated by Django 5.1.2 on 2024-10-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_increment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
