# Generated by Django 5.1.2 on 2024-10-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_userprofile_last_increment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
